### ISSUE TITLE
Fails to Upload from iOS

### ISSUE THREAD

**Issue by shonin** [bradleyg/django-s3direct#97] opened 2017-02-15 00:08 UTC
iPad Pro iOS 10
Browsers: Chrome, Safari
`DEBUG=True`

```
boto3==1.4.4
botocore==1.5.7
Django==1.10.4
django-s3direct==0.4.8
```

After trying to upload the file, I just get the generic "Sorry, failed to upload file" popup.

I can confirm that the uploading works from a desktop, as well as in Chrome on Android. 

This is running on Heroku, and the only thing I see when running `$ heroku logs` is this successful `POST`:
```
2017-02-14T23:55:44.964302+00:00 heroku[router]: at=info method=POST path="/s3direct/get_upload_params/" host=myapp.herokuapp.com request_id=c97b09ab-bea3-480e-9254-c4ba93934645 fwd="some.ip.here" dyno=web.1 connect=1ms service=53ms status=200 bytes=1113
```

I'd love some tips on how to debug further

**Comment by lili2311** [comment] 2017-03-13 22:20
You can try connecting your device to a laptop, opening Safari and in the Develop menu selecting your device to debug with, then in the browser try to upload as normal and check the network tab. This should now be using your device so you can see the error message.

I am having an issue with Safari at the moment not uploading will post if I find the cause in case it is related.

**Comment by bradleyg** [comment] 2017-03-14 09:05
Thanks, Lili.

Elliot, can you confirm this fix worked for you too?

**Comment by bradleyg** [comment] 2017-03-20 11:34
Closing out, let me know if this is still an issue.

**Closed by bradleyg** 2017-03-20 11:34 UTC
